# cloudbuild.docker.yaml  (replace the args section only)
steps:
- name: gcr.io/cloud-builders/docker
  args: ['build',
         '-f', '${_SERVICE}-service/Dockerfile',
         '-t', '${_IMAGE}',
         '${_SERVICE}-service' ]          #  ←  context = service dir
images:
- '${_IMAGE}'
